### ISSUE TITLE
Command bar autocomplete

### ISSUE THREAD

**Issue by mikeful** [dr-soft/dred#3]
It would be helpful to have autocomplete for command bar commands and config variables. Maybe also hints for command parameters.

**Comment by mackron** [comment]
Yes, I have that on my todo list among many other improvements. It's shouldn't actually take too long to do this so I'll give it a higher priority and get on to it soon.

**Comment by ghost** [comment]
@mackron Hi I've been looking for smaller projects to practice programming with as I've been practicing with larger ones mostly so far in higher level languages.

Do you think given that I know basic C syntax (I went through cs50, so pointers, structs, etc. too) I could add this feature? I guess you have an array of strings containing potential command bar commands and config variables, and then when the tab key is pressed it'll list out the ones that match the characters you've entered so far?

Point me to the right place in the code to add this if you think I can help and I'll get to work :)

**Comment by mackron** [comment]
@ashleypt Yes, you're most welcome to give it a go, and I'd appreciate it! Just keep in mind that the GUI code is not my greatest work :)

Commands are auto-generated using a pre-build tool, so take a look at dred_autogenerated.c which is where all auto-generated code is dumped. In there is a DRED_COMMAND_COUNT constant and g_CommandNames[] array which you can use for iteration. I don't yet generate information about the parameters for each command so you'll need to leave parameter information out for the moment.

For the GUI it'll be a bit more complex because it's a bit messy at the moment. There's two main objects to deal with: windows (Win32/GTK windows) and GUI controls. Take a look at dred_platform_layer.h/c for windows and gui/dred_gui.h/c for controls. Controls are organized into a standard parent/child hierarchy like you'd expect, and each window has it's own top-level control which you should use as the parent for any custom controls. Take a look at gui/dred_button.c for an example on using the GUI code.

To start off with, I'd recommend figuring out how to create a popup-style window. Currently I have APIs for creating top-level windows and dialogs, but none for popups. You'll probably want something like dred_window_create_popup(). You'll probably want to put a global reference to the popup window in the dred_context object (dred_context.h/c).

There's probably a few more things I've missed, but you'll figure it out! :) Happy to help you out wherever needed.

**Comment by ghost** [comment]
@mackron Hi, I submitted a PR for the readme but my plate is a bit too full to do this solo right now as I'm also learning android and wordpress development while also contributing to a rails project... pretty intensive learning regimen lol. Feel free to assign me any lighter issues in the future too :)

feel bad about it as this was a really interesting issue for me - figuring out that code would have been a great challenge for me but I'm diffusing my efforts a little too much :(

on the other hand if you want to pair program this, I would *love* to work on it with you - seeing how a more experienced developer works with a large codebase and working in real time would be a big boost for my skills

**Comment by ghost** [comment]
@mackron sorry to send an extra note, but just wanted to let you know I had to edit my original comment a bit to specify that on the other hand I'd be happy to pair program/collaborate on this one with you when you do it

**Comment by mackron** [comment]
Yeah that's no problem at all. What I'll probably do is get an initial version working which just lists the command names - that should be pretty simple. After that, if you're interested, we can work on some of the more complicated stuff like handling parameters and command-specific auto-complete (like a more user-friendly "open" command which I've been meaning to do since forever).

**Comment by ghost** [comment]
@mackron sounds like a great plan :) let me know when you're ready

**Comment by mackron** [comment]
The basics of an auto-complete system for commands is in (has been for a while). This is just an initial pass and I'll be adding more to it such as parameter hints in future versions.
